### PR TITLE
[New Sample]Add sample app to show uploading attachments when creating a request.

### PR DESCRIPTION
**Pull request by brendan-fahy**
## Changes
* Add a new sample app that uses the `UploadProvider` and the `RequestProvider` to create a request with attachments retrieved using `Belvedere`. 

## Notes

* The same 2-step strategy used by the Support SDK is used here - the attachments are uploaded as soon as `Belvedere` returns them. 
* For simplicity of code, the sample app shows a blocking `ProgressDialog` until all attachment upload requests have finished (unlike the Support SDK, which allows continued interaction). 
* All Java code is contained within the `UploadAttachmentActivity`. 

## Reviewers 
@baz8080 @schlan @ndobri 

## FYI
@KevinLambe @mathewcropper

### CODE REVIEW

**Comment by baz8080** [comment]
LGTM, will you add a small README please?

**Comment by brendan-fahy** [comment]
OOOOOOOOH CAN DO

**Comment by brendan-fahy** [comment]
@baz8080 readme added.

**Comment by baz8080** [comment]
👍

**Pull request merged**
